# Generated by Django 4.2.17 on 2025-01-15 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='zip',
            field=models.PositiveIntegerField(),
        ),
    ]
