# Generated by Django 4.2.17 on 2025-01-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image_search', '0002_person_date_alter_person_age_alter_person_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='zip',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
