# Generated by Django 4.2.17 on 2025-01-15 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image_search', '0003_alter_person_age_alter_person_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
